- job:
    name: satellite6-release-compose
    logrotate:
      daysToKeep: -1
      numToKeep: 32
    node: sesame
    parameters:
      - choice:
          name: version
          choices:
            - 6.2.0
          description: "Satellite version to build for"
          default: 6.2.0
      - string:
          name: organization
          description: "Satellite organization containing the product"
          default: "Sat6-CI"
    builders:
      - conditional-step:
          condition-kind: always
          steps:
            - trigger-builds:
                - project: satellite6-generate-compose
                  current-parameters: true
                  predefined-parameters:
                    rhel=rhel7
                  block: true
                  block-thresholds:
                    build-step-failure-threshold: FAILURE
                    unstable-threshold: UNSTABLE
                    failure-threshold: FAILURE
      - conditional-step:
          condition-kind: current-status
          condition-worst: SUCCESS
          condition-best: SUCCESS
          steps:
            - trigger-builds:
                - project: satellite6-generate-compose
                  current-parameters: true
                  predefined-parameters:
                    rhel=rhel6
                  block: true
                  block-thresholds:
                    build-step-failure-threshold: FAILURE
                    unstable-threshold: UNSTABLE
                    failure-threshold: FAILURE
      - conditional-step:
          condition-kind: current-status
          condition-worst: SUCCESS
          condition-best: SUCCESS
          steps:
            - trigger-builds:
                - project: satellite6-generate-compose
                  current-parameters: true
                  predefined-parameters:
                    rhel=rhel5
                  block: true
                  block-thresholds:
                    build-step-failure-threshold: FAILURE
                    unstable-threshold: UNSTABLE
                    failure-threshold: FAILURE
    publishers:
      - trigger-parameterized-builds:
          - project: satellite6-release-sync-product
            current-parameters: true
            condition: SUCCESS
